### ISSUE TITLE
Best practice: Forbid usage of declare(strict_types=1) in some files

### ISSUE THREAD

**Issue by mmunz** [sabbelasichon/typo3-rector#1705]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html#best-practices-for-ext-tables-php-and-ext-localconf-php states for ext_tables.php and ext_localconf.php:

"The same goes for declare(strict_types=1) and similar directives which must be placed at the very top of files: once all files of all extensions are merged, this condition is not fulfilled anymore leading to errors. So these must never be used here."

**Comment by tmotyl** [comment]
not sure if this would be in scope of typo3-rector or saschaegerer/phpstan-typo3

**Comment by sabbelasichon** [comment]
@mmunz Thanks for that. Especially because i did that mistake during my demo and didn´t pay attention for it. But never did it in real projects. I would say this should be part of saschaegerer/phpstan-typo3 as a rule check rather than be part of typo3-rector. Of course, there are some intersections of these tools.
