### ISSUE TITLE
Scoping of phar file

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1912]
In order to have a real isolated phar file with conflictfree classnames we should scope the phar file

**Comment by sabbelasichon** [comment]
@TomasVotruba This one gives me a real headache. Most of the arising problems which our users have are coming from dependency conflicts. I know that rector offers the prefixed version. I really would like to provide also a prefixed version but bundled in a .phar file. I tried it multiple times and i am always getting different problems. Could you provide any insights on how to solve this the best possible way?

**Comment by TomasVotruba** [comment]
Hi, welcome to the club :) in the end it took like 50 % of the energy of whole year Rector development.
While the scoped version and phar are identical in features. Just instead of `wget rector.phar`, there is `wget composer.phar && composer require ...`.

So we decided to drop it an actually do some features: https://getrector.org/blog/2020/12/28/rector-09-released#debuggable-rector-prefixed

If you still want to try it, here are few notes about Phar WTF in Symfony:  https://tomasvotruba.com/blog/2019/12/02/how-to-box-symfony-app-to-phar-without-killing-yourself/
