### ISSUE TITLE
Convert TypoScript includes to newer configuration

### ISSUE THREAD

**Issue by einpraegsam** [sabbelasichon/typo3-rector#2453]
To reduce technical dept, changing those lines in TypoScript files would help:

```
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:gridelements/Configuration/TypoScript/setup.typoscript">
<INCLUDE_TYPOSCRIPT: source="DIR:EXT:in2grids/Configuration/TypoScript/Elements" extensions="ts">
```

into:

```
@import 'EXT:gridelements/Configuration/TypoScript/setup.typoscript'
@import 'EXT:in2grids/Configuration/TypoScript/Elements/*.ts'
```

Documentation: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/TypoScriptSyntax/Syntax/Includes.html since version 9 for TYPO3

**Comment by sabbelasichon** [comment]
For files this is already possible with this rule:
https://github.com/sabbelasichon/typo3-rector/blob/main/src/FileProcessor/TypoScript/Visitors/FileIncludeToImportStatementVisitor.php

For directories this is not possible because the new behaviour is not compatible. No recursive lookup. We would have to split it in multiple statements. We decided not to do so.

**Comment by einpraegsam** [comment]
Oh thx, then I do not completely understand which rules can be used and where to find it. I will go back to documentation :+1:

**Comment by sabbelasichon** [comment]
The list grows and grows. So not that easy to find it:
https://github.com/sabbelasichon/typo3-rector/blob/main/docs/all_rectors_overview.md#fileincludetoimportstatementvisitor

**Comment by einpraegsam** [comment]
Ok, can be included via $services->set(). Nevertheless this is still missing in my eyes:
- Convert includes from complete folders
- Can be used also in TSConfig (not tested yet)
