### ISSUE TITLE
PHP Fatal in ValidateAnnotationRector for @validate RegularExpression

### ISSUE THREAD

**Issue by sgrossberndt** [sabbelasichon/typo3-rector#2807]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.15       |

## Minimal PHP Code Causing Issue

Rector fatals with
```
  11/968 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   1%
PHP Fatal error:  Uncaught TypeError: preg_match_all() expects parameter 2 to be string, null given in /home/sgrossberndt/rector-instance/vendor/rector/rector/vendor/ssch/typo3-rector/src/Rector/v9/v3/ValidateAnnotationRector.php:107
Stack trace:
#0 /home/sgrossberndt/rector-instance/vendor/rector/rector/vendor/ssch/typo3-rector/src/Rector/v9/v3/ValidateAnnotationRector.php(107): preg_match_all('#\\s*(?P<optionN...', NULL, NULL)
#1 /home/sgrossberndt/rector-instance/vendor/rector/rector/vendor/ssch/typo3-rector/src/Rector/v9/v3/ValidateAnnotationRector.php(67): Ssch\TYPO3Rector\Rector\v9\v3\ValidateAnnotationRector->c
```

when trying to fix a `@validate` RegularExpression like `RegularExpression (regularExpression = '/^[A-z0-9]{32}$/')`, e.g.:

EXT:myext/Classes/Domain/Model/MyDomainModel.php
```
class MyDomainModel extends AbstractEntity {

	/**
	 * @var string
	 * @validate RegularExpression (regularExpression = '/^[A-z0-9]{32}$/')
	 */
	protected $configId;
}
```

## Expected Behaviour

No fatal, convert the `@validate` Expression.

**Comment by sabbelasichon** [comment]
@sgrossberndt Thanks. Does this even work for you in the old installation, because i have copied the regular expression to parse the annotation from the TYPO3 core, and a whitespace between the validatorName and the starting parenthesis is not foreseen. I have tried to fix it on my side to ignore the whitespace between it. Could you try it out locally first by placing this change to your local rector installation: https://github.com/sabbelasichon/typo3-rector/pull/2808/files#diff-051b5706f5f25463f9e4d45a3c289839f37aecfc5a18741bd387da70d720dfa5R118

**Comment by sgrossberndt** [comment]
Just verified it worked in the old installation and your patch works as well. Thanks a lot!

**Comment by sabbelasichon** [comment]
Thank you
