### ISSUE TITLE
Why not allow Rector version ranges?

### ISSUE THREAD

**Issue by mbrodala** [sabbelasichon/typo3-rector#3439]
Since https://github.com/sabbelasichon/typo3-rector/pull/3206 this package does not allow version ranges for the `rector/rector` package anymore but uses fixed versions instead.

I would like to know why exactly.

Background: given e.g. version 0.17.3 of `rector/rector` Composer chooses the ancient version v0.11.46 of `ssch/typo3-rector` which does not work. Installing a 1.x version of this package is impossible unless one downgrades Rector accordingly.

If there was a case where a patch version did introduce breaking changes then the author of Rector should be asked if this was intentional. According to semver for `0.x` a bump of the minor version would be required here. Thus e.g. a version range like `^0.17.0` would be safe.

**Comment by helsner** [comment]
The original rector package is not that precise regarding breaking changes and versioning.
So basically **every** version that is newly released is breaking to our package.
To prevent frustration because typo3-rector does not work we pin the version to a working one with our codebase.
As rector/rector comes via dependency by us, it is not often the case that there are version issues.
Also because typo3-rector is mostly used for upgrades and then removed i would guess? So it does not conflict with the original rector in "normal" development i would expect.

**Comment by mbrodala** [comment]
I can understand the former. Unfortunate that SemVer is still not respected properly nowadays.

As for the latter I normally run Rector dry run as part of our CI, thus TYPO3 Rector would be a permanent dependency, not just for upgrades/migrations. Given the current state we'd be locked to a Rector version and miss possibly important updates.

Not sure how to solve this conflict ATM ...
